// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modelos;

#nullable disable

namespace Modelos.Migrations
{
    [DbContext(typeof(ContextoConversor))]
    partial class ContextoConversorModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entidades.Personas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("FechaNacimiento")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Personas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FechaNacimiento = new DateTime(1998, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Pedro",
                            Password = "Contraseña",
                            Telefono = "948230430",
                            Username = "Paco1"
                        },
                        new
                        {
                            Id = 2,
                            FechaNacimiento = new DateTime(1995, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Ana",
                            Password = "Contraseña",
                            Telefono = "123456789",
                            Username = "Paco2"
                        },
                        new
                        {
                            Id = 3,
                            FechaNacimiento = new DateTime(1990, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Luis",
                            Password = "Contraseña",
                            Telefono = "987654321",
                            Username = "Paco3"
                        },
                        new
                        {
                            Id = 4,
                            FechaNacimiento = new DateTime(1987, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "María",
                            Password = "Contraseña",
                            Telefono = "555123789",
                            Username = "Paco4"
                        },
                        new
                        {
                            Id = 5,
                            FechaNacimiento = new DateTime(2005, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Juan",
                            Password = "Contraseña",
                            Telefono = "777888999",
                            Username = "Paco5"
                        },
                        new
                        {
                            Id = 6,
                            FechaNacimiento = new DateTime(2002, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Laura",
                            Password = "Contraseña",
                            Telefono = "333444555",
                            Username = "Paco6"
                        },
                        new
                        {
                            Id = 7,
                            FechaNacimiento = new DateTime(1978, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Carlos",
                            Password = "Contraseña",
                            Telefono = "999111222",
                            Username = "Paco7"
                        },
                        new
                        {
                            Id = 8,
                            FechaNacimiento = new DateTime(1983, 7, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Marta",
                            Password = "Contraseña",
                            Telefono = "444555666",
                            Username = "Paco8"
                        },
                        new
                        {
                            Id = 9,
                            FechaNacimiento = new DateTime(2000, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Andrés",
                            Password = "Contraseña",
                            Telefono = "888999000",
                            Username = "Paco9"
                        },
                        new
                        {
                            Id = 10,
                            FechaNacimiento = new DateTime(1970, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Isabel",
                            Password = "Contraseña",
                            Telefono = "222333444",
                            Username = "Paco10"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
